### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by youpiyoup** [yushulx/crawl-404#1]
Hi, 

I have an error at run de script :   
File "404crawler.py", line 28
print(f'404 analysis completed. Crawling depth: {self.crawl_depth}. Total unique links: {len(self.all_links)}')
                                                                                                                 ^
SyntaxError: invalid syntax

thanks for your help :)

**Comment by yushulx** [comment]
@youpiyoup format the code and then retry

**Comment by youpiyoup** [comment]
okay juste change the run -> python3
